name: github-actions-tests
run-name: ${{ github.actor }} Run demo workflow
on: [push, workflow_dispatch]
jobs:
  OnPush:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }} and action is ${{github.event}} or ${{github.event}} or $GITHUB_EVENT_NAME."
      - uses: actions/checkout@v4
      - name:  Run unittest
        run: ./gradlew test --no-build-cache
      - name:  Run application
        run: ./gradlew run
      - name: Send Slack notification
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Hello, this is a message from GitHub Actions! Branch: ${{ github.ref }}" from user "${{ github.actor }} event "${{github.action }}"}' ${{ secrets.SLACK_WEBHOOK_URL }}



