name: github-actions-tests
run-name: ${{ github.actor }}Run unittest
on: [push]
jobs:
  OnPush:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./gradlew test --no-build-cache


